//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTR_MODDING_TOOL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DOTR_MODDING_TOOL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Eyes White Dragon
        ///Seiyaryu
        ///Blue-Eyes Ultimate Dragon
        ///Kaiser Dragon
        ///Blackland Fire Dragon
        ///Koumori Dragon
        ///Curse of Dragon 
        ///Red Eyes Black Dragon
        ///Darkfire Dragon
        ///B. Skull Dragon
        ///Tri-Horned Dragon
        ///Serpent Night Dragon
        ///Mikazukinoyaiba
        ///Yamadron
        ///Meteor B Dragon
        ///Tyhone #2  
        ///Ryu-Ran
        ///Manga Ryu-Ran
        ///Crawling Dragon  
        ///Meteor Dragon
        ///B. Dragon Jungle King
        ///Baby Dragon
        ///Winged Dragon, Guardian of the Fortress #1
        ///Gaia the Dragon Champion 
        ///Thousand Dragon
        ///Yamatano Dragon Scroll
        ///Petit Dragon 
        ///One [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardList {
            get {
                return ResourceManager.GetString("CardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_1_2LT {
            get {
                object obj = ResourceManager.GetObject("DeckRank_1_2LT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_10_ADM {
            get {
                object obj = ResourceManager.GetObject("DeckRank_10_ADM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_11_SADM {
            get {
                object obj = ResourceManager.GetObject("DeckRank_11_SADM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_12_SD {
            get {
                object obj = ResourceManager.GetObject("DeckRank_12_SD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_2_1LT {
            get {
                object obj = ResourceManager.GetObject("DeckRank_2_1LT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_3_CPT {
            get {
                object obj = ResourceManager.GetObject("DeckRank_3_CPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_4_MAJ {
            get {
                object obj = ResourceManager.GetObject("DeckRank_4_MAJ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_5_LTC {
            get {
                object obj = ResourceManager.GetObject("DeckRank_5_LTC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_6_COL {
            get {
                object obj = ResourceManager.GetObject("DeckRank_6_COL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_7_BG {
            get {
                object obj = ResourceManager.GetObject("DeckRank_7_BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_8_RADM {
            get {
                object obj = ResourceManager.GetObject("DeckRank_8_RADM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeckRank_9_VADM {
            get {
                object obj = ResourceManager.GetObject("DeckRank_9_VADM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
